<?php

use yii\db\Migration;

/**
 * Handles the creation of table `city`.
 */
class m181019_045802_create_city_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('city', [
            'id' => $this->primaryKey(),
			'region_id' => $this->integer(),
			'name' => $this->string(),
			'lat' => $this->double(),
			'long' => $this->double(),
        ]);

        $this->batchInsert('city', ['id', 'region_id', 'name', 'lat', 'long'], [
			array('id' => '1','region_id' => '3','name' => 'Аккурган','lat' => NULL,'long' => NULL),
			array('id' => '2','region_id' => '3','name' => 'Алмалык','lat' => NULL,'long' => NULL),
			array('id' => '3','region_id' => '3','name' => 'Ахангаран','lat' => NULL,'long' => NULL),
			array('id' => '4','region_id' => '3','name' => 'Бекабад','lat' => NULL,'long' => NULL),
			array('id' => '5','region_id' => '3','name' => 'Болшой Чимган','lat' => NULL,'long' => NULL),
			array('id' => '6','region_id' => '3','name' => 'Бука','lat' => NULL,'long' => NULL),
			array('id' => '7','region_id' => '3','name' => 'Чарвак','lat' => NULL,'long' => NULL),
			array('id' => '8','region_id' => '3','name' => 'Чиназ','lat' => NULL,'long' => NULL),
			array('id' => '9','region_id' => '3','name' => 'Чирчик','lat' => NULL,'long' => NULL),
			array('id' => '10','region_id' => '3','name' => 'Сукок','lat' => NULL,'long' => NULL),
			array('id' => '11','region_id' => '3','name' => 'Дурмень','lat' => NULL,'long' => NULL),
			array('id' => '12','region_id' => '3','name' => 'Дустабад','lat' => NULL,'long' => NULL),
			array('id' => '13','region_id' => '3','name' => 'Эшангузар','lat' => NULL,'long' => NULL),
			array('id' => '14','region_id' => '3','name' => 'Газалкент','lat' => NULL,'long' => NULL),
			array('id' => '15','region_id' => '3','name' => 'Гузалкент','lat' => NULL,'long' => NULL),
			array('id' => '16','region_id' => '3','name' => 'Гульбахор','lat' => NULL,'long' => NULL),
			array('id' => '17','region_id' => '3','name' => 'Искандар','lat' => NULL,'long' => NULL),
			array('id' => '18','region_id' => '3','name' => 'Карасу','lat' => NULL,'long' => NULL),
			array('id' => '19','region_id' => '3','name' => 'Келес','lat' => NULL,'long' => NULL),
			array('id' => '20','region_id' => '3','name' => 'Кибрай','lat' => NULL,'long' => NULL),
			array('id' => '21','region_id' => '3','name' => 'Красногорск','lat' => NULL,'long' => NULL),
			array('id' => '22','region_id' => '3','name' => 'Назарбек','lat' => NULL,'long' => NULL),
			array('id' => '23','region_id' => '3','name' => 'Нурафшан(Тойтепа)','lat' => NULL,'long' => NULL),
			array('id' => '24','region_id' => '3','name' => 'Паркент','lat' => NULL,'long' => NULL),
			array('id' => '25','region_id' => '3','name' => 'Пискент','lat' => NULL,'long' => NULL),
			array('id' => '26','region_id' => '3','name' => 'Салар','lat' => NULL,'long' => NULL),
			array('id' => '27','region_id' => '3','name' => 'Ташморе','lat' => NULL,'long' => NULL),
			array('id' => '28','region_id' => '3','name' => 'Туркестан','lat' => NULL,'long' => NULL),
			array('id' => '29','region_id' => '3','name' => 'Уртааул','lat' => NULL,'long' => NULL),
			array('id' => '30','region_id' => '3','name' => 'Ходжикент','lat' => NULL,'long' => NULL),
			array('id' => '31','region_id' => '3','name' => 'Янгиабад','lat' => NULL,'long' => NULL),
			array('id' => '32','region_id' => '3','name' => 'Янгибазар','lat' => NULL,'long' => NULL),
			array('id' => '33','region_id' => '3','name' => 'Янгиюль','lat' => NULL,'long' => NULL),
			array('id' => '34','region_id' => '3','name' => 'Зафар','lat' => NULL,'long' => NULL),
			array('id' => '35','region_id' => '3','name' => 'Зангиата','lat' => NULL,'long' => NULL),
			array('id' => '36','region_id' => '1','name' => 'Акалтын','lat' => NULL,'long' => NULL),
			array('id' => '37','region_id' => '1','name' => 'Алтинкуль','lat' => NULL,'long' => NULL),
			array('id' => '38','region_id' => '1','name' => 'Андижан','lat' => NULL,'long' => NULL),
			array('id' => '39','region_id' => '1','name' => 'Асака','lat' => NULL,'long' => NULL),
			array('id' => '40','region_id' => '1','name' => 'Аханбабаев','lat' => NULL,'long' => NULL),
			array('id' => '41','region_id' => '1','name' => 'Балыкчи','lat' => NULL,'long' => NULL),
			array('id' => '42','region_id' => '1','name' => 'Боз','lat' => NULL,'long' => NULL),
			array('id' => '43','region_id' => '1','name' => 'Булакбаши','lat' => NULL,'long' => NULL),
			array('id' => '44','region_id' => '1','name' => 'Карасу','lat' => NULL,'long' => NULL),
			array('id' => '45','region_id' => '1','name' => 'Куйганьяр','lat' => NULL,'long' => NULL),
			array('id' => '46','region_id' => '1','name' => 'Кургантепа','lat' => NULL,'long' => NULL),
			array('id' => '47','region_id' => '1','name' => 'Мархамат','lat' => NULL,'long' => NULL),
			array('id' => '48','region_id' => '1','name' => 'Пайтуг','lat' => NULL,'long' => NULL),
			array('id' => '49','region_id' => '1','name' => 'Пахтаабад','lat' => NULL,'long' => NULL),
			array('id' => '50','region_id' => '1','name' => 'Шахрихан','lat' => NULL,'long' => NULL),
			array('id' => '51','region_id' => '1','name' => 'Ханабад','lat' => NULL,'long' => NULL),
			array('id' => '52','region_id' => '1','name' => 'Ходжаабад','lat' => NULL,'long' => NULL),
			array('id' => '53','region_id' => '2','name' => 'Алат','lat' => NULL,'long' => NULL),
			array('id' => '54','region_id' => '2','name' => 'Бухара','lat' => NULL,'long' => NULL),
			array('id' => '55','region_id' => '2','name' => 'Гааласия','lat' => NULL,'long' => NULL),
			array('id' => '56','region_id' => '2','name' => 'Газли','lat' => NULL,'long' => NULL),
			array('id' => '57','region_id' => '2','name' => 'Гиждуван','lat' => NULL,'long' => NULL),
			array('id' => '58','region_id' => '2','name' => 'Каган','lat' => NULL,'long' => NULL),
			array('id' => '59','region_id' => '2','name' => 'Каракуль','lat' => NULL,'long' => NULL),
			array('id' => '60','region_id' => '2','name' => 'Караулбазар','lat' => NULL,'long' => NULL),
			array('id' => '61','region_id' => '2','name' => 'Ромитан','lat' => NULL,'long' => NULL),
			array('id' => '62','region_id' => '2','name' => 'Шафиркан','lat' => NULL,'long' => NULL),
			array('id' => '63','region_id' => '2','name' => 'Вабкент','lat' => NULL,'long' => NULL),
			array('id' => '64','region_id' => '2','name' => 'Жондор','lat' => NULL,'long' => NULL),
			array('id' => '65','region_id' => '5','name' => 'Айдаркуль','lat' => NULL,'long' => NULL),
			array('id' => '66','region_id' => '5','name' => 'Баландчакир','lat' => NULL,'long' => NULL),
			array('id' => '67','region_id' => '5','name' => 'Даштабод','lat' => NULL,'long' => NULL),
			array('id' => '68','region_id' => '5','name' => 'Дустлик','lat' => NULL,'long' => NULL),
			array('id' => '69','region_id' => '5','name' => 'Джизах','lat' => NULL,'long' => NULL),
			array('id' => '70','region_id' => '5','name' => 'Гагарин','lat' => NULL,'long' => NULL),
			array('id' => '71','region_id' => '5','name' => 'Галлаарал','lat' => NULL,'long' => NULL),
			array('id' => '72','region_id' => '5','name' => 'Голиблар','lat' => NULL,'long' => NULL),
			array('id' => '73','region_id' => '5','name' => 'Марджанбулак','lat' => NULL,'long' => NULL),
			array('id' => '74','region_id' => '5','name' => 'Пахтакор','lat' => NULL,'long' => NULL),
			array('id' => '75','region_id' => '5','name' => 'Учтепа','lat' => NULL,'long' => NULL),
			array('id' => '76','region_id' => '5','name' => 'Усмат','lat' => NULL,'long' => NULL),
			array('id' => '77','region_id' => '5','name' => 'Янгикишлак','lat' => NULL,'long' => NULL),
			array('id' => '78','region_id' => '5','name' => 'Заамин','lat' => NULL,'long' => NULL),
			array('id' => '79','region_id' => '5','name' => 'Зафарабад','lat' => NULL,'long' => NULL),
			array('id' => '80','region_id' => '5','name' => 'Зарбдар','lat' => NULL,'long' => NULL),
			array('id' => '81','region_id' => '6','name' => 'Акмагнит','lat' => NULL,'long' => NULL),
			array('id' => '82','region_id' => '6','name' => 'Беруни','lat' => NULL,'long' => NULL),
			array('id' => '83','region_id' => '6','name' => 'Бустан','lat' => NULL,'long' => NULL),
			array('id' => '84','region_id' => '6','name' => 'Чимбай','lat' => NULL,'long' => NULL),
			array('id' => '85','region_id' => '6','name' => 'Каныкуль','lat' => NULL,'long' => NULL),
			array('id' => '86','region_id' => '6','name' => 'Кегейли','lat' => NULL,'long' => NULL),
			array('id' => '87','region_id' => '6','name' => 'Кунград','lat' => NULL,'long' => NULL),
			array('id' => '88','region_id' => '6','name' => 'Магнит','lat' => NULL,'long' => NULL),
			array('id' => '89','region_id' => '6','name' => 'Муйнак','lat' => NULL,'long' => NULL),
			array('id' => '90','region_id' => '6','name' => 'Шуманай','lat' => NULL,'long' => NULL),
			array('id' => '91','region_id' => '6','name' => 'Тахиаташ','lat' => NULL,'long' => NULL),
			array('id' => '92','region_id' => '6','name' => 'Тахтакупыр','lat' => NULL,'long' => NULL),
			array('id' => '93','region_id' => '6','name' => 'Торткуль','lat' => NULL,'long' => NULL),
			array('id' => '94','region_id' => '6','name' => 'Ходжейли','lat' => NULL,'long' => NULL),
			array('id' => '95','region_id' => '7','name' => 'Бешкент','lat' => NULL,'long' => NULL),
			array('id' => '96','region_id' => '7','name' => 'Чиракчи','lat' => NULL,'long' => NULL),
			array('id' => '97','region_id' => '7','name' => 'Дехканабад','lat' => NULL,'long' => NULL),
			array('id' => '98','region_id' => '7','name' => 'Гузар','lat' => NULL,'long' => NULL),
			array('id' => '99','region_id' => '7','name' => 'Камаши','lat' => NULL,'long' => NULL),
			array('id' => '100','region_id' => '7','name' => 'Карашина','lat' => NULL,'long' => NULL),
			array('id' => '101','region_id' => '7','name' => 'Карши','lat' => NULL,'long' => NULL),
			array('id' => '102','region_id' => '7','name' => 'Касан','lat' => NULL,'long' => NULL),
			array('id' => '103','region_id' => '7','name' => 'Касби','lat' => NULL,'long' => NULL),
			array('id' => '104','region_id' => '7','name' => 'Китаб','lat' => NULL,'long' => NULL),
			array('id' => '105','region_id' => '7','name' => 'Мурабек','lat' => NULL,'long' => NULL),
			array('id' => '106','region_id' => '7','name' => 'Муглан','lat' => NULL,'long' => NULL),
			array('id' => '107','region_id' => '7','name' => 'Шахрисабз','lat' => NULL,'long' => NULL),
			array('id' => '108','region_id' => '7','name' => 'Талимарджан','lat' => NULL,'long' => NULL),
			array('id' => '109','region_id' => '7','name' => 'Яккабаг','lat' => NULL,'long' => NULL),
			array('id' => '110','region_id' => '7','name' => 'Янги Миришкор','lat' => NULL,'long' => NULL),
			array('id' => '111','region_id' => '7','name' => 'Янги-Нишан','lat' => NULL,'long' => NULL),
			array('id' => '112','region_id' => '8','name' => 'Багат','lat' => NULL,'long' => NULL),
			array('id' => '113','region_id' => '8','name' => 'Чалыш','lat' => NULL,'long' => NULL),
			array('id' => '114','region_id' => '8','name' => 'Гурлен','lat' => NULL,'long' => NULL),
			array('id' => '115','region_id' => '8','name' => 'Караул','lat' => NULL,'long' => NULL),
			array('id' => '116','region_id' => '8','name' => 'Кошкупыр','lat' => NULL,'long' => NULL),
			array('id' => '117','region_id' => '8','name' => 'Питнак','lat' => NULL,'long' => NULL),
			array('id' => '118','region_id' => '8','name' => 'Шават','lat' => NULL,'long' => NULL),
			array('id' => '119','region_id' => '8','name' => 'Ургенч','lat' => NULL,'long' => NULL),
			array('id' => '120','region_id' => '8','name' => 'Ханка','lat' => NULL,'long' => NULL),
			array('id' => '121','region_id' => '8','name' => 'Хазарасп','lat' => NULL,'long' => NULL),
			array('id' => '122','region_id' => '8','name' => 'Хива','lat' => NULL,'long' => NULL),
			array('id' => '123','region_id' => '8','name' => 'Янгиарык','lat' => NULL,'long' => NULL),
			array('id' => '124','region_id' => '9','name' => '   Чартак','lat' => NULL,'long' => NULL),
			array('id' => '125','region_id' => '9','name' => 'Челак','lat' => NULL,'long' => NULL),
			array('id' => '126','region_id' => '9','name' => 'Чуст','lat' => NULL,'long' => NULL),
			array('id' => '127','region_id' => '9','name' => 'Джумашуй','lat' => NULL,'long' => NULL),
			array('id' => '128','region_id' => '9','name' => 'Касансай','lat' => NULL,'long' => NULL),
			array('id' => '129','region_id' => '9','name' => 'Наманган','lat' => NULL,'long' => NULL),
			array('id' => '130','region_id' => '9','name' => 'Пап','lat' => NULL,'long' => NULL),
			array('id' => '131','region_id' => '9','name' => 'Ташбулак','lat' => NULL,'long' => NULL),
			array('id' => '132','region_id' => '9','name' => 'Туракурган','lat' => NULL,'long' => NULL),
			array('id' => '133','region_id' => '9','name' => 'Учкурган','lat' => NULL,'long' => NULL),
			array('id' => '134','region_id' => '9','name' => 'Хаккулабад','lat' => NULL,'long' => NULL),
			array('id' => '135','region_id' => '10','name' => 'Бешрабат','lat' => NULL,'long' => NULL),
			array('id' => '136','region_id' => '10','name' => 'Канимех','lat' => NULL,'long' => NULL),
			array('id' => '137','region_id' => '10','name' => 'Кармана','lat' => NULL,'long' => NULL),
			array('id' => '138','region_id' => '10','name' => 'Кызылтепа','lat' => NULL,'long' => NULL),
			array('id' => '139','region_id' => '10','name' => 'Навои','lat' => NULL,'long' => NULL),
			array('id' => '140','region_id' => '10','name' => 'Тамдыбулак','lat' => NULL,'long' => NULL),
			array('id' => '141','region_id' => '10','name' => 'Учкудук','lat' => NULL,'long' => NULL),
			array('id' => '142','region_id' => '10','name' => 'Янгирабат','lat' => NULL,'long' => NULL),
			array('id' => '143','region_id' => '10','name' => 'Зарафшан','lat' => NULL,'long' => NULL),
			array('id' => '144','region_id' => '11','name' => 'Акташ','lat' => NULL,'long' => NULL),
			array('id' => '145','region_id' => '11','name' => 'Булунгур','lat' => NULL,'long' => NULL),
			array('id' => '146','region_id' => '11','name' => 'Чилек','lat' => NULL,'long' => NULL),
			array('id' => '147','region_id' => '11','name' => 'Дарбанд','lat' => NULL,'long' => NULL),
			array('id' => '148','region_id' => '11','name' => 'Джамбай','lat' => NULL,'long' => NULL),
			array('id' => '149','region_id' => '11','name' => 'Джума','lat' => NULL,'long' => NULL),
			array('id' => '150','region_id' => '11','name' => 'Гузалкент','lat' => NULL,'long' => NULL),
			array('id' => '151','region_id' => '11','name' => 'Гюлабад','lat' => NULL,'long' => NULL),
			array('id' => '152','region_id' => '11','name' => 'Иштыхан','lat' => NULL,'long' => NULL),
			array('id' => '153','region_id' => '11','name' => 'Каттакурган','lat' => NULL,'long' => NULL),
			array('id' => '154','region_id' => '11','name' => 'Кушрабад','lat' => NULL,'long' => NULL),
			array('id' => '155','region_id' => '11','name' => 'Лаиш','lat' => NULL,'long' => NULL),
			array('id' => '156','region_id' => '11','name' => 'Нурабад','lat' => NULL,'long' => NULL),
			array('id' => '157','region_id' => '11','name' => 'Пайарык','lat' => NULL,'long' => NULL),
			array('id' => '158','region_id' => '11','name' => 'Пайшанба','lat' => NULL,'long' => NULL),
			array('id' => '159','region_id' => '11','name' => 'Самарканд','lat' => NULL,'long' => NULL),
			array('id' => '160','region_id' => '11','name' => 'Тайлак','lat' => NULL,'long' => NULL),
			array('id' => '161','region_id' => '11','name' => 'Ургут','lat' => NULL,'long' => NULL),
			array('id' => '162','region_id' => '11','name' => 'Зиадин','lat' => NULL,'long' => NULL),
			array('id' => '163','region_id' => '12','name' => 'Ангор','lat' => NULL,'long' => NULL),
			array('id' => '164','region_id' => '12','name' => 'Байсун','lat' => NULL,'long' => NULL),
			array('id' => '165','region_id' => '12','name' => 'Бандихон','lat' => NULL,'long' => NULL),
			array('id' => '166','region_id' => '12','name' => 'Денау','lat' => NULL,'long' => NULL),
			array('id' => '167','region_id' => '12','name' => 'Джаркурган','lat' => NULL,'long' => NULL),
			array('id' => '168','region_id' => '12','name' => 'Карлук','lat' => NULL,'long' => NULL),
			array('id' => '169','region_id' => '12','name' => 'Кизирик','lat' => NULL,'long' => NULL),
			array('id' => '170','region_id' => '12','name' => 'Кумкурган','lat' => NULL,'long' => NULL),
			array('id' => '171','region_id' => '12','name' => 'Музрабад','lat' => NULL,'long' => NULL),
			array('id' => '172','region_id' => '12','name' => 'Сариасия','lat' => NULL,'long' => NULL),
			array('id' => '173','region_id' => '12','name' => 'Сарык','lat' => NULL,'long' => NULL),
			array('id' => '174','region_id' => '12','name' => 'Шаргунь','lat' => NULL,'long' => NULL),
			array('id' => '175','region_id' => '12','name' => 'Шерабад','lat' => NULL,'long' => NULL),
			array('id' => '176','region_id' => '12','name' => 'Шурчи','lat' => NULL,'long' => NULL),
			array('id' => '177','region_id' => '12','name' => 'Термез','lat' => NULL,'long' => NULL),
			array('id' => '178','region_id' => '12','name' => 'Учкызыл','lat' => NULL,'long' => NULL),
			array('id' => '179','region_id' => '12','name' => 'Узун','lat' => NULL,'long' => NULL),
			array('id' => '180','region_id' => '12','name' => 'Халкабад','lat' => NULL,'long' => NULL),
			array('id' => '181','region_id' => '13','name' => 'Бахт','lat' => NULL,'long' => NULL),
			array('id' => '182','region_id' => '13','name' => 'Баяут','lat' => NULL,'long' => NULL),
			array('id' => '183','region_id' => '13','name' => 'Cырдарья','lat' => NULL,'long' => NULL),
			array('id' => '184','region_id' => '13','name' => 'Гулистан','lat' => NULL,'long' => NULL),
			array('id' => '185','region_id' => '13','name' => 'Навруз','lat' => NULL,'long' => NULL),
			array('id' => '186','region_id' => '13','name' => 'Сайхун','lat' => NULL,'long' => NULL),
			array('id' => '187','region_id' => '13','name' => 'Сардоба','lat' => NULL,'long' => NULL),
			array('id' => '188','region_id' => '13','name' => 'Ширин','lat' => NULL,'long' => NULL),
			array('id' => '189','region_id' => '13','name' => 'Теренозек','lat' => NULL,'long' => NULL),
			array('id' => '190','region_id' => '13','name' => 'Хаваст','lat' => NULL,'long' => NULL),
			array('id' => '191','region_id' => '13','name' => 'Янгиер','lat' => NULL,'long' => NULL),
			array('id' => '192','region_id' => '13','name' => 'Янгиёр','lat' => NULL,'long' => NULL),
			array('id' => '193','region_id' => '4','name' => ' Алтыарык','lat' => NULL,'long' => NULL),
			array('id' => '194','region_id' => '4','name' => 'Багдад','lat' => NULL,'long' => NULL),
			array('id' => '195','region_id' => '4','name' => 'Бешарык','lat' => NULL,'long' => NULL),
			array('id' => '196','region_id' => '4','name' => 'Дангара','lat' => NULL,'long' => NULL),
			array('id' => '197','region_id' => '4','name' => 'Фергана','lat' => NULL,'long' => NULL),
			array('id' => '198','region_id' => '4','name' => 'Коканд','lat' => NULL,'long' => NULL),
			array('id' => '199','region_id' => '4','name' => 'Кува','lat' => NULL,'long' => NULL),
			array('id' => '200','region_id' => '4','name' => 'Кувасай','lat' => NULL,'long' => NULL),
			array('id' => '201','region_id' => '4','name' => 'Лангар','lat' => NULL,'long' => NULL),
			array('id' => '202','region_id' => '4','name' => 'Маргилан','lat' => NULL,'long' => NULL),
			array('id' => '203','region_id' => '4','name' => 'Навбахор','lat' => NULL,'long' => NULL),
			array('id' => '204','region_id' => '4','name' => 'Раван','lat' => NULL,'long' => NULL),
			array('id' => '205','region_id' => '4','name' => 'Риштан','lat' => NULL,'long' => NULL),
			array('id' => '206','region_id' => '4','name' => 'Шахимардан','lat' => NULL,'long' => NULL),
			array('id' => '207','region_id' => '4','name' => 'Ташлак','lat' => NULL,'long' => NULL),
			array('id' => '208','region_id' => '4','name' => 'Яйпан','lat' => NULL,'long' => NULL),
			array('id' => '209','region_id' => '4','name' => 'Янги Маргилан','lat' => NULL,'long' => NULL),
			array('id' => '210','region_id' => '4','name' => 'Янгикурган','lat' => NULL,'long' => NULL),
			array('id' => '211','region_id' => '4','name' => 'Язъяван','lat' => NULL,'long' => NULL),
			array('id' => '212','region_id' => '14','name' => 'Бектемирский район','lat' => NULL,'long' => NULL),
			array('id' => '213','region_id' => '14','name' => 'Мирабадский район','lat' => NULL,'long' => NULL),
			array('id' => '214','region_id' => '14','name' => 'Мирзо-Улугбекский район','lat' => NULL,'long' => NULL),
			array('id' => '215','region_id' => '14','name' => 'Сергелийский район','lat' => NULL,'long' => NULL),
			array('id' => '216','region_id' => '14','name' => 'Олмазорский район','lat' => NULL,'long' => NULL),
			array('id' => '217','region_id' => '14','name' => 'Учтепинский район','lat' => NULL,'long' => NULL),
			array('id' => '218','region_id' => '14','name' => 'Шайхонтохурский район','lat' => NULL,'long' => NULL),
			array('id' => '219','region_id' => '14','name' => 'Яшнободский район','lat' => NULL,'long' => NULL),
			array('id' => '220','region_id' => '14','name' => 'Чиланзарский район','lat' => NULL,'long' => NULL),
			array('id' => '221','region_id' => '14','name' => 'Юнусабадский район','lat' => NULL,'long' => NULL),
			array('id' => '222','region_id' => '14','name' => 'Яккасарайский район','lat' => NULL,'long' => NULL),
			array('id' => '223','region_id' => '6','name' => 'Нукус','lat' => NULL,'long' => NULL),
			array('id' => '224','region_id' => '3','name' => 'Ангрен','lat' => NULL,'long' => NULL)
		]);

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('city');
    }
}
