<?php
namespace common\modules\categories\controllers;

use Yii;
use yii\base\Controller;
use yii\helpers\ArrayHelper;

class CategoriesController extends Controller{
    public function actions()
    {
        return ArrayHelper::merge(parent::actions(),[
            'index' => [
                'class' => 'common\modules\categories\actions\CategoriesAction'
            ]
        ]); // TODO: Change the autogenerated stub
    }
}