<?php
/**
 * Created by PhpStorm.
 * User: xurshid
 * Date: 2/7/19
 * Time: 2:42 PM
 */
/**
 * @api {get} /messages/my  Мой Сообшения
 * @apiName MyMessagesList
 * @apiGroup Messages
 *
 * @apiSuccess {Object} messages Всех Сообшения пользовителя
 *
 */
namespace api\modules\v1\controllers;

use api\components\ApiController;
use common\models\Message;
use common\models\MessageSearch;
use common\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\UnauthorizedHttpException;

class MessageController extends ApiController
{

    public $modelClass = Message::class;
    public $searchModelClass = MessageSearch::class;

    /**
     * @return array|ActiveDataProvider
	 */
    public function actions()
    {
        $actions =  parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index'], $actions['view']);
        return $actions;
    }

    public function actionMy(){
        $user = User::authorize();
        if($user){
            $query = $user->profile->getMessages();
            if($query){
                $dataProvider = new ActiveDataProvider([
                    'query' => $query,
                    'sort' => [
                        'defaultOrder' => [
                            'id' => SORT_DESC,
                        ]
                    ],
                ]);
                return $dataProvider;
            }else{
                return ['message'=>'Нет сообщения'];
            }

        }else{
            throw new UnauthorizedHttpException('Вы не авторизование!');
        }

    }


}
