<?php
/**
 *  @author Jakhar <jakharbek@gmail.com>
 *  @company OKS Technologies <info@oks.uz>
 *  @package YoshlarTV
 */

namespace common\modules\menu\models;


use common\behaviors\SlugBehavior;
use Yii;
use yii\caching\TagDependency;
use \yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\behaviors\SluggableBehavior;
//Языки
use common\modules\langs\models\Langs;
use common\modules\langs\components\ModelBehavior;
//Категории
/**
 * This is the model class for table "menu".
 *
 * @property int $menu_id Идентификатор
 * @property string $title Название
 * @property int $type Тип
 * @property int $alias Тип
 * @property string $lang_hash Хеш языка
 * @property int $lang Язык
 *
 * @property Langs $lang0
 * @property MenuItems[] $menuItems
 */
class Menu extends \yii\db\ActiveRecord
{
    const SCENARIO_SEARCH = "search";
    const STATUS_ACTIVE = 1;


    /**
     * @return array
     */
    public function behaviors()
        {
        return ArrayHelper::merge(parent::behaviors(),[
            'lang' => [
                'class' => ModelBehavior::className(),
                'attribute_hash' => 'lang_hash',
                'fill' => [
                    'alias' => '',
                ],
            ],
            'slug' => [
                'class' => SlugBehavior::className(),
                'attribute' => 'alias',
                'attribute_title'=> 'title',
            ],
        ]); // TODO: Change the autogenerated stub

    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menu';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'lang'], 'default', 'value' => null],
            [['type', 'lang'], 'integer'],
            [['alias'],'safe'],
            [['title', 'lang_hash','alias'], 'string', 'max' => 255],
            [['lang'], 'exist', 'skipOnError' => true, 'targetClass' => Langs::className(), 'targetAttribute' => ['lang' => 'lang_id']],
        ];
    }

    /**
     * @return array
     */
    public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'menu_id' => Yii::t('backend','Menu ID'),
            'title' => Yii::t('backend','Title'),
            'type' => Yii::t('backend','Type')
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLang()
    {
        return $this->hasOne(Langs::className(), ['lang_id' => 'lang'])->inverseOf('menus');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuItems()
    {
        return $this->hasMany(MenuItems::className(), ['menu_id' => 'menu_id'])->inverseOf('menu')->orderBy(['sort' => SORT_ASC]);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenuItemsParents()
    {
        return $this->hasMany(MenuItems::className(), ['menu_id' => 'menu_id'])->onCondition(['menu_items.menu_item_parent_id' => NULL])->orderBy(['sort' => SORT_ASC])->inverseOf('menu');
    }

    /**
     * @inheritdoc
     * @return MenuQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new MenuQuery(get_called_class());
    }

    /**
     * @param string $menu_alias
     * @return mixed
     */
    public static function cacheHttpTag($menu_alias = ""){
        $mneu = self::find()->alias($menu_alias);
        return MenuItems::find()->andWhere(['menu_id' => $mneu->menu_id])->orderBy(['sort' => SORT_DESC])->one()->{MenuItems::primaryKey()[0]};
    }

    public function fields() {
        return array(
            'title',
            'childs' => function($model) {
                return $model->menuItemsParents;
            },
        );
    }

}
